apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: 
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.env.user }}.nathan-demo.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
            path: /
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - {{ .Values.env.user }}.nathan-demo.com
    secretName: myingress-cert # < cert-manager will store the created certificate in this secret.
