name: cluster-init
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_JWT }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    # - name: Terraform Apply
    #   id: plan
    #   if: github.event_name == 'pull_request'
    #   run: terraform apply -auto-approve -target="google_container_cluster.primary" -var 'project=${{ secrets.GKE_PROJECT }}' -var 'username=${{ github.actor }}' -input=false

    # # Configure Docker to use the gcloud command-line tool as a credential
    # # helper for authentication
    # - run: |-
    #     gcloud --quiet auth configure-docker

    # # Get the GKE credentials so we can deploy to the cluster
    # - uses: google-github-actions/get-gke-credentials@v1
    #   with:
    #     cluster_name: ${{ github.actor }}-cluster
    #     location: "europe-west1-b"
    #     # credentials: ${{ secrets.GKE_SA_KEY }}
 
    #  - name: Terraform Apply
    #   id: plan
    #   if: github.event_name == 'pull_request'
    #   run: terraform apply -auto-approve -var 'project=${{ secrets.GKE_PROJECT }}' -var 'username=${{ github.actor }}' -input=false
